### ISSUE TITLE
Receiving this error: Failed to execute 'send' on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by jcmoodle** [brickfield/moodle-mod_board#136]
Hello, 

We have a Moodle 4.1.10 (Build: 20240422) site running on an ubuntu 20.04 server.  We are using NGINX and PHP 8.1. We have the version '1.401.03 (Build 2022040112)' of the mod_board plugin installed.  

We can add the mod_board activity to a course, however, when we click on the activity it tries to send it's payload it seems that there is an empty string or file. 

This is what we are seeing:
`Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://www.domain.com/lib/ajax/service.php?sesskey=o8uaAwZ2il&info=mod_board_get_configuration'.
    at Object.send (https://www.domain.com/lib/javascript.php/1714501038/lib/jquery/jquery-3.6.1.min.js:2:82858)
    at Function.ajax (https://www.domain.com/lib/javascript.php/1714501038/lib/jquery/jquery-3.6.1.min.js:2:78435)
    at Object.call (https://www.domain.com/lib/requirejs.php/1714501038/core/first.js:20:2746)
    at https://www.domain.com/lib/requirejs.php/1714501038/core/first.js:2699:305
    at Object.initialize (https://www.domain.com/lib/requirejs.php/1714501038/core/first.js:2699:454)
    at https://www.domain.com/mod/board/view.php?id=61831&forceview=1:803:85
    at Object.execCb (https://www.domain.com/lib/javascript.php/1714501038/lib/requirejs/require.min.js:5:12861)
    at b.check (https://www.domain.com/lib/javascript.php/1714501038/lib/requirejs/require.min.js:5:6615)
    at b.enable (https://www.domain.com/lib/javascript.php/1714501038/lib/requirejs/require.min.js:5:9363)
    at b.init (https://www.domain.com/lib/javascript.php/1714501038/lib/requirejs/require.min.js:5:5721)`

And

`{
  "error": "Coding error detected, it must be fixed by a programmer: Invalid json in request: Syntax error",
  "errorcode": "codingerror",
  "stacktrace": "* line 63 of /lib/ajax/service.php: coding_exception thrown\n",
  "debuginfo": "\nError code: codingerror",
  "reproductionlink": "https://www.domain.com/"
}`

Give us a place to look at / more insight on this, what could be causing this?

**Comment by learningtechnologyservices** [comment]
Hi there @jcmoodle , many thanks for reporting this issue, and we'll start investigating shortly! Regards Karen

**Comment by learningtechnologyservices** [comment]
Hi again, @jcmoodle !

Would it be possible for the plugin to be completely uninstalled and then reinstalled again, on the Moodle site in question? We want to rule out any upgrade issues with database records. If the error still appears after that, we'll try to investigate further then.

Regards
Karen

**Comment by learningtechnologyservices** [comment]
Hi there, we have just listed new releases for Board, for 4.1/4.2/4.3 & 4.4/4.5. 

If this issue is still occurring with your site with these new releases, please re-open this issue. TIA!

**Comment by daph-j** [comment]
Hi @learningtechnologyservices , I've seen this issue still occurring on Moodle 4.5.13, mod_board version 1.405.05.

All I did to reproduce the error was install the plugin, create a new instance of the activity, then view it. Could you re-open this issue?
